render:
  # Use 1 for FullHD resolution and 2 for 4k
  resolutionScale: 1
  # The size of tiles in pixels. These are multiplied by the resolution scale to get the actual size.
  tileSize: 120
# These options are passed directly to PIXI.Application when initializing
pixiOptions:
  antialias: true
panels:
  editor:
    # If true, the policy overlay will be visible all the time. This also hides the "View policy"
    # button in the AI training panel.
    policyOverlayAlwaysVisible: false
    # If true, the policy overlay will show arrows to indicate the direction of the policy.
    policyOverlayShowArrows: true
    # If true, the policy overlay will show the value at the cell.
    policyOverlayShowText: true
    # If true, the policy overlay will show a background that partially obscures the tile
    # underneath to make the text more readable.
    policyOverlayShowBackground: true
    # If true, the reset button in the AI control panel will also reset the maze.
    aiResetButtonResetsMaze: false
  training:
    # If true, the "FF" button will be a "toggle" type button that switches between two states
    # on each press. Otherwise, it will be a "hold" button that only activates while pressed.
    useToggleFFButton: false
    # If true, the "View policy" button will be a "toggle" type button that switches between two
    # states on each press. Otherwise, it will be a "hold" button that only activates while pressed.
    useToggleViewPolicyButton: false
    # If true, the reset button in the AI control panel will also reset the Exploration/Exploitation
    # slider.
    aiResetButtonResetsExplorationRate: false
sentry:
  # Sentry DSN for error tracking
  # Override this value through settings-exhibit.yml, not here.
  # see README.md for alternatives.
  # dsn: "xxx"
