# The default language to use.
defaultLanguage: en
# Languages that will be offered to the user in <iso code>: <language name> format.
# Each of these should have a translation file in the tr directory.
languages:
  en: English
  de: Deutsch
  nl: Nederlands
