ui:
  maze:
    # Stroke and color of maze cells
    cellStrokeSize: 3
    cellStrokeColor: '#000000'
    # This setting allows configuring how the start cell will be rendered through the
    # definition of a tile type with id 0 in the tiles.yml file.
    # If set to false, the start tile will be rendered with the stroke defined below
    startCellStyleViaTileConfig: false
    # Stroke and color of the start cell
    startCellStrokeSize: 10
    startCellStrokeColor: '#99ff99'
    startCellFillColor: '#ffffff'
    # Stroke and color of the border around the maze
    borderStrokeSize: 0
    borderStrokeColor: '#000000'
